### ISSUE TITLE
passkey-coinbase not working during registration

### ISSUE THREAD

**Issue by shuther** [keepassxreboot/keepassxc#10648]
## Overview
While trying to add a passkey from coinbase, the passkey gets added to keepassxc but the website thinks it failed:
It could be linked to other opened issues or coinbase but worked fine for google.

## Steps to Reproduce
1. go to: https://accounts.coinbase.com/security/settings
2. add a new passkey
3. with KeepasssXC, Accept the DB (I have multiple opened)
4. accept the passkey or click update
5. copinbse believed it failed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the website (coinbase) should know that it is ok.

## Actual Behavior
coinbase screen:
```
Set up your Passkey
Once you begin registration, your browser should prompt you to register your passkey. Follow the instructions to complete registration.
Retry button
```

## Context
console log
```
[NOTE]: # ( Give us any additional information you may have. )
UserLeap] (ERR-444) Failed to report error to API TypeError: Failed to fetch
    at acc.app.78af72ecb5c91106c9b2.js:2:39000
    at new Promise (<anonymous>)
    at t.fetch (acc.app.78af72ecb5c91106c9b2.js:2:38971)
    at acc.app.78af72ecb5c91106c9b2.js:2:39000
    at new Promise (<anonymous>)
    at t.fetch (acc.app.78af72ecb5c91106c9b2.js:2:38971)
    at web-controller-sdk.js:1:18837
    at c (web-controller-sdk.js:1:45716)
    at g._invoke (web-controller-sdk.js:1:45511)
    at S.forEach.t.<computed> [as next] (web-controller-sdk.js:1:46139)
test.e._isBreadcrumbTypeEnabled.console.<computed> @ acc.app.78af72ecb5c91106c9b2.js:2
acc.app.78af72ecb5c91106c9b2.js:2 UserLeap - Disabled: Failed to set userId
acc.app.78af72ecb5c91106c9b2.js:2 [UserLeap] (ERR-444) Failed to report error to API TypeError: Failed to fetch
    at acc.app.78af72ecb5c91106c9b2.js:2:39000
    at new Promise (<anonymous>)
    at t.fetch (acc.app.78af72ecb5c91106c9b2.js:2:38971)
    at acc.app.78af72ecb5c91106c9b2.js:2:39000
    at new Promise (<anonymous>)
    at t.fetch (acc.app.78af72ecb5c91106c9b2.js:2:38971)
    at web-controller-sdk.js:1:18837
    at c (web-controller-sdk.js:1:45716)
    at g._invoke (web-controller-sdk.js:1:45511)
    at S.forEach.t.<computed> [as next] (web-controller-sdk.js:1:46139)
test.e._isBreadcrumbTypeEnabled.console.<computed> @ acc.app.78af72ecb5c91106c9b2.js:2
2acc.81956.f24e10061a7e3bb047db.js:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'credProps')
    at M (acc.81956.f24e10061a7e3bb047db.js:11:73589)
    at acc.81956.f24e10061a7e3bb047db.js:11:420503
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by varjolintu** [comment]
Already reported here: https://github.com/keepassxreboot/keepassxc/issues/10374

**Comment by shuther** [comment]
@varjolintu the problem happened with brave/chromium, not only firefox (not sure how to update the table)
