### ISSUE TITLE
RFE: Support FIPS mode

### ISSUE THREAD

**Issue by opoplawski** [keepassxreboot/keepassxc#2007]
keepassxc fails to run in FIPS mode.

## Expected Behavior
keepassxc runs with a limited set of ciphers.

## Current Behavior
keepassxc exits with:
```
Crypto::checkAlgorithms: GCRY_CIPHER_TWOFISH not found.
```
## Possible Solution
Make checks for specific ciphers non-fatal.

## Steps to Reproduce (for bugs)
1.  Boot EL7 system with fips=1
2. run keepassxc

## Context
Certain U.S. Federal agencies require systems to run in FIPS mode - where only FIPS certified cryptographic routines are available.

## Debug Info

KeePassXC - 2.3.3

Operating system: RHEL7
CPU architecture: x86_64
Kernel: 3.10.0-862.3.2.el7.x86_64

**Comment by opoplawski** [comment]
This also may not be sufficient - after hacking out the twofish (and salsa/chacha20 because I'm trying to get this to work on EL7 with libgcrypt 1.5.3) I get:
```
keepassxc: ath.c:268: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.
#0  0x00007ffff58e9207 in raise () from /lib64/libc.so.6
#1  0x00007ffff58ea8f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff58e2026 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff58e20d2 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff69dfbda in _gcry_ath_mutex_lock (lock=0x7ffff6c4ec78 <fsm_lock>) at ath.c:268
#5  0x00007ffff69ddfbd in lock_fsm () at fips.c:225
#6  0x00007ffff69de75d in _gcry_fips_is_operational () at fips.c:367
#7  0x00007ffff69d71fc in gcry_cipher_encrypt (h=0x7fffd0005000, out=0x7fffd0014b08, outsize=16, in=0x0, inlen=0) at visibility.c:590
#8  0x00005555555af8ed in SymmetricCipherGcrypt::processInPlace (this=0x7fffd0013ff0, data=..., rounds=50000)
    at /usr/src/debug/keepassxc-2.3.3/src/crypto/SymmetricCipherGcrypt.cpp:199
#9  0x00005555555ffa99 in processInPlace (rounds=50000, data=..., this=0x7fffe10f07d0) at /usr/src/debug/keepassxc-2.3.3/src/crypto/SymmetricCipher.h:77
#10 AesKdf::transformKeyRaw (key=..., seed=..., rounds=50000, result=0x7fffffffbda0) at /usr/src/debug/keepassxc-2.3.3/src/crypto/kdf/AesKdf.cpp:96
#11 0x0000555555600c66 in QtConcurrent::StoredFunctorCall4<bool, bool (*)(QByteArray const&, QByteArray const&, int, QByteArray*), QByteArray, QByteArray, int, QByteArray*>::runFunctor (this=0x5555565f4bf0) at /usr/include/qt5/QtConcurrent/qtconcurrentstoredfunctioncall.h:1508
#12 0x000055555560393f in QtConcurrent::RunFunctionTask<bool>::run (this=0x5555565f4bf0) at /usr/include/qt5/QtConcurrent/qtconcurrentrunbase.h:108
#13 0x00007ffff632dd0e in QThreadPoolThread::run() () from /lib64/libQt5Core.so.5
#14 0x00007ffff6330b71 in QThreadPrivate::start(void*) () from /lib64/libQt5Core.so.5
#15 0x00007ffff569edd5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff59b1b3d in clone () from /lib64/libc.so.6
```
Which may be due to keepassxc using internal routines rather than openssl functions.  Not sure, see https://www.libssh2.org/mail/libssh2-devel-archive-2014-07/0012.shtml

**Comment by TheZ3ro** [comment]
You can't remove Salsa20 since it's mandatory (it's used for encrypting single entries in the database)

For more info take a look at #325

**Comment by droidmonkey** [comment]
We will not be implementing this.
