### ISSUE TITLE
KeePassXC-Browser error

### ISSUE THREAD

**Issue by mzr** [keepassxreboot/keepassxc#2418]
I've just installed KeePassXC-Browser extension and it gives me error:
`Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?`

Here is log form chromium debug console:
```
keepass.js:895 Connecting to native messaging host org.keepassxc.keepassxc_browser
browser-polyfill.min.js:1 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) Error
    at B (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/browser-polyfill.min.js:1:8152)
    at page.initSettings.then (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/event.js:109:9)
B @ browser-polyfill.min.js:1
browser-polyfill.min.js:1 Failed to send onMessage rejected reply Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:102:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at responseCallback (extensions::messaging:210:16)
    at F.G.then.H (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/browser-polyfill.min.js:1:8305)
F.G.then.catch.H @ browser-polyfill.min.js:1
11keepass.js:979 Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?
2keepass.js:979 Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?
```

NativeMessagingHosts file:
```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

keepass-proxy is running.

## Expected Behavior

Really don't know. I've never used it before. It should connect to KeePassXC I guess?

## Current Behavior

Described above.

## Steps to Reproduce (for bugs)

1. Install KeePassXC from manjaro community repository
2. Install chromium extension.
3. Enable browser integration for chromium.
3. Voilla

Yeah. I don't know how to describe it better. I think I didn't do anything special.

## Context

I'm just trying to make it work. Didn't used it before.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.14.77-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by mzr** [comment]
I am doing some debugging and I found out that extension fails when it tries to `changePublicKeys`.

I evaluated some variables:
```
keepass.serverPublicKey
""
keepass.isKeePassXCAvailable
false
keepass.isConnected
true
```
Looks like `verifyKeyResponse` (`keepass.js:626`) returns false and `tab && page.tabs[tab.id]` evaluates to `true`. I don't know what it means, but maybe it would be helpful for someone more knowledgeable about this project.

**Comment by mzr** [comment]
My bad...
Didn't read the [instructions](https://keepassxc.org/docs/keepassxc-browser-migration/) carefully enough.

> Open KeePassXC and unlock your database (this is important, the following steps won’t work if your database is locked or KeePassXC isn’t running).
