### ISSUE TITLE
I'm unable to run the program if compiled with Clang and AddressSanitizer turned on

### ISSUE THREAD

**Issue by brainplot** [keepassxreboot/keepassxc#2428]
In the latest snapshot, I was not able to run the program with the AddressSanitizer turned on.
I thought that one of the commits in the `develop` branch had introduced this so I checked out the `master` branch, and the problem persisted.

## Expected Behavior
Being able to run the program cleanly with AddressSanitizer on

## Current Behavior
KeepassXC, compiled with clang, produces the following output _upon process start_, and then exits immediately.
```
=================================================================
==7040==ERROR: AddressSanitizer: odr-violation (0x55b0def125e0):
  [1] size=48 'vtable for AutoTypeChar' /home/gianluca/Projects/keepassxc/src/autotype/AutoTypeAction.cpp
  [2] size=48 'vtable for AutoTypeChar' /home/gianluca/Projects/keepassxc/src/autotype/AutoTypeAction.cpp
These globals were registered at these points:
  [1]:
    #0 0x55b0de5c9f01  (/home/gianluca/Projects/build-keepassxc-Desktop-Debug/src/keepassxc+0x12cf01)
    #1 0x7f6a37df085d  (/home/gianluca/Projects/build-keepassxc-Desktop-Debug/src/autotype/xcb/libkeepassx-autotype-xcb.so+0x1b85d)

  [2]:
    #0 0x55b0de5c9f01  (/home/gianluca/Projects/build-keepassxc-Desktop-Debug/src/keepassxc+0x12cf01)
    #1 0x55b0dea5e6bd  (/home/gianluca/Projects/build-keepassxc-Desktop-Debug/src/keepassxc+0x5c16bd)

==7040==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'vtable for AutoTypeChar' at /home/gianluca/Projects/keepassxc/src/autotype/AutoTypeAction.cpp
==7040==ABORTING
```
I know what an ODR violation is, but I couldn't find where `AutoTypeChar` is supposedly defined twice.

If compiled with GCC instead, the program runs but gives the following output `upon process exit` (i.e. as soon as I close program).
```
=================================================================
==11058==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 3 object(s) allocated from:
    #0 0x7fd4a42f6f19 in operator new[](unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:93
    #1 0x7fd4a23fc398 in qstrdup(char const*) (/usr/lib/libQt5Core.so.5+0xc6398)

SUMMARY: AddressSanitizer: 136 byte(s) leaked in 3 allocation(s).
```
I'm not sure the error GCC spits out is related to the KeepassXC's code, as it looks like it belongs to some of the Qt internals.

## Possible Solution
No idea. I've never worked with an address sanitizer so I'm not familiar with its error messages, which I find a bit cryptic to read.

## Steps to Reproduce (for bugs)
Compile the program with either compiler passing `-DWITH_ASAN` to CMake, and run it.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.16-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

#### Compiler version
```
➜ clang++ --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
➜ g++ --version
g++ (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by phoerious** [comment]
You need to suppress ODR violation errors when compiling with Clang. It doesn't work well with our dynamic plugin loading.
