### ISSUE TITLE
Browser addon does not detect KeePassXC

### ISSUE THREAD

**Issue by Awem** [keepassxreboot/keepassxc#2446]
## What I did
- I installed KeePassXC 2.3.4 on Windows 10 Home 1803
- I added KeePassXCBrowser 1.3.0 to Firefox 63
- I set registry keys etc. according to [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)

## What happens
The browser addons prints
```
Connecting to native messaging host org.keepassxc.keepassxc_browser
Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?
```
The addon settings page prints
```
You are running KeePassXC version: unknown
```
However, KeePassXC is running with enabled support for Firefox. Also the Firefox process launched `keepassxc-proxy.exe` from the installation directory of KeePassXC.

How can I debug further?

Update:
The connections works, if I disable the proxy in KeePassXC for Firefox. Is there any debugging info for `keepassxc-proxy.exe`?

**Comment by varjolintu** [comment]
Can you check that the `keepassxc-proxy.exe` stays open all the time when opening the browser or when making a reload?

**Comment by Awem** [comment]
I'm using Firefox Portable, but regular KeePassXC from MSI Installer (64-bit).
If I start FF, it launches `keepassxc-proxy.exe` as a child process. This child process is killed once I close FF or once I click "Reload"in the KeePassXC addon dialog. However, in the later case a new `keepassxc-proxy.exe` is launched as well.

**Comment by benyar** [comment]
Same issue.  I can connect one time, but upon closing KeepassXC and the browser I have to start over with connecting the plugin to the database.  This also occurs if the connection times out, without closing either the browser or the database.

Mint 19
Browser:  Chromium 70 (stable) or Firefox 63.0
KeepassXC 2.3.1 (from official Mint/Ubuntu repository)
Keepassxc-browser 1.3.0 from each browser's extension store

keepassxc-proxy is running when a browser is launched
Keepassxc is configured for browser integration

I followed the troubleshooting guide linked above
Firefox plugin output:
```
Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:150
InvalidStateError: RTCPeerConnection is gone (did you enter Offline mode?)
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:895:5
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
webrequest.js:111
Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC? keepass.js:979:5
Unknown localization message optionsignoredsitesremove translate.js:8
Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?
keepass.js:979:5
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:895:5
Server public key: +rsYAa4qSplHJLphSOJ74uVdoWHLdZzRgbc1m9YkqUA= keepass.js:634:17
Error 8: KeePassXC association failed, try again keepass.js:979:5
Error: Could not establish connection. Receiving end does not exist. event.js:162:13
Error 8: KeePassXC association failed, try again keepass.js:979:5
The resource at “https://go.pardot.com/.well-known/dnt-policy.txt” was blocked because content blocking is enabled.[Learn More] _generated_background_page.html
Error 5: Timeout or not connected to KeePassXC. keepass.js:979:5
Error: Nonce compare failed keepass.js:963:9
Error 8: KeePassXC association failed, try again keepass.js:979:5 
```

Chromium output:
```
Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:634 Server public key: w1BluO+w6rZFGXmJdP2X08M51FBTY92+fWGuHlJ2+Dk=
browser-polyfill.min.js:1 Returning a Promise is the preferred way to send a reply from an onMessage/onMessageExternal listener, as the sendResponse will be removed from the specs (See https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onMessage) Error
    at B (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/browser-polyfill.min.js:1:8152)
    at Object.kpxcEvent.onUpdateAvailableKeePassXC (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/event.js:209:5)
    at browser.tabs.get.then (chrome-extension://oboonakemofpalcgghocfoadofidjkkk/background/event.js:72:21)
B @ browser-polyfill.min.js:1
kpxcEvent.onUpdateAvailableKeePassXC @ event.js:209
browser.tabs.get.then @ event.js:72
Promise.then (async)
kpxcEvent.invoke @ event.js:46
kpxcEvent.onMessage @ event.js:13
(anonymous) @ browser-polyfill.min.js:1
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
messageListener @ extensions::messaging:240
EventImpl.dispatchToListener @ extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ extensions::utils:138
EventImpl.dispatch_ @ extensions::event_bindings:387
EventImpl.dispatch @ extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ extensions::utils:138
dispatchOnMessage @ extensions::messaging:392
keepass.js:979 Error 8: KeePassXC association failed, try again
```

This behavior is not happening for me in Windows (Google Chrome browser only)

**Comment by droidmonkey** [comment]
@Awem still an issue?

**Comment by Awem** [comment]
Maybe, but I can't check anymore. I retired my last Windows machine and am only using Linux now. Everything works fine on Arch Linux. So feel free to close this. Thanks anyway, for the great software!
