### ISSUE TITLE
Element Desktop can no longer access its keys through org.freedesktop.secrets on 2.7.0

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#7562]
Hi there,

After updating to KeePassXC 2.7.0 on Arch Linux, I’ve tested several usages and all work fine excepted the one mentioned in the title.

Element Desktop stores and retrieves its encryption keys through org.freedesktop.secrets, just as some other software do. It works fine on 2.6.6, but after restarting KeePassXC on 2.7.0, it does ask to get access (through a new menu btw, which list more precisely the software and proposes option to allow or deny), but once granted all encrypted room are seen encrypted with a message that “encryption is unavailable”.

I don’t know what could be useful to debug this, but just ask what you need and I’ll try to get that for you.

**Comment by droidmonkey** [comment]
which option did you pick in the dialog?

**Comment by Aetf** [comment]
Run the following while Element Desktop starts and retrieves passwords. It will capture all communications between KeePassXC and Element Desktop.

`dbus-monitor "destination=org.freedesktop.secrets" "sender=org.freedesktop.secrets"`

Don't forget to mask any byte arrays in the output, it may contain your secret key.

**Comment by ArchangeGabriel** [comment]
> which option did you pick in the dialog?

Tried both that looked like “allow” (one was something like “allow selected” and the other “allow all and future”).

> Run the following while Element Desktop starts and retrieves passwords. It will capture all communications between KeePassXC and Element Desktop.
> 
> `dbus-monitor "destination=org.freedesktop.secrets" "sender=org.freedesktop.secrets"`
> 
> Don't forget to mask any byte arrays in the output, it may contain your secret key.

So I’ve done that on both 2.6.6 and 2.7 in case the comparison would be useful:
<details>
<summary>2.6.6 log</summary>

```
method call time=1647951801.162589 sender=:1.73 -> destination=:1.32 serial=28 path=/org/freedesktop/secrets; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.Secret.Service"
method return time=1647951801.162748 sender=:1.32 -> destination=:1.73 serial=54 reply_serial=28
   array [
      dict entry(
         string "Collections"
         variant             array [
               object path "/org/freedesktop/secrets/collection/password"
            ]
      )
   ]
method call time=1647951801.165665 sender=:1.73 -> destination=:1.32 serial=29 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=OpenSession
   string "dh-ietf1024-sha256-aes128-cbc-pkcs7"
   variant       array of bytes [
         <redacted>
      ]
method call time=1647951801.165892 sender=:1.32 -> destination=org.freedesktop.DBus serial=55 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.73'"
method call time=1647951801.169365 sender=:1.32 -> destination=org.freedesktop.DBus serial=56 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionUnixProcessID
   string ":1.73"
method return time=1647951801.169393 sender=org.freedesktop.DBus -> destination=:1.32 serial=26 reply_serial=56
   uint32 8406
method return time=1647951801.171729 sender=:1.32 -> destination=:1.73 serial=57 reply_serial=29
   variant       array of bytes [
         <redacted>
      ]
   object path "/org/freedesktop/secrets/session/<redacted>"
method call time=1647951801.174265 sender=:1.73 -> destination=:1.32 serial=30 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "account"
         string "<redacted>"
      )
      dict entry(
         string "service"
         string "element.io"
      )
      dict entry(
         string "xdg:schema"
         string "org.freedesktop.Secret.Generic"
      )
   ]
method return time=1647951801.174726 sender=:1.32 -> destination=:1.73 serial=58 reply_serial=30
   array [
   ]
   array [
   ]
method call time=1647951801.175360 sender=:1.73 -> destination=:1.32 serial=31 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "account"
         string "<redacted>"
      )
      dict entry(
         string "service"
         string "riot.im"
      )
      dict entry(
         string "xdg:schema"
         string "org.freedesktop.Secret.Generic"
      )
   ]
method return time=1647951801.175703 sender=:1.32 -> destination=:1.73 serial=59 reply_serial=31
   array [
   ]
   array [
   ]
method call time=1647951801.225988 sender=:1.73 -> destination=:1.32 serial=32 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "account"
         string "<redacted>"
      )
      dict entry(
         string "service"
         string "element.io"
      )
      dict entry(
         string "xdg:schema"
         string "org.freedesktop.Secret.Generic"
      )
   ]
method return time=1647951801.227138 sender=:1.32 -> destination=:1.73 serial=60 reply_serial=32
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
   array [
   ]
method call time=1647951801.227604 sender=:1.73 -> destination=:1.32 serial=33 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=GetSecrets
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
   object path "/org/freedesktop/secrets/session/80302ec0a72a40b592e8afaca5e31146"
method call time=1647951801.228156 sender=:1.32 -> destination=org.freedesktop.DBus serial=61 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionUnixProcessID
   string ":1.73"
method return time=1647951801.228166 sender=org.freedesktop.DBus -> destination=:1.32 serial=27 reply_serial=61
   uint32 8406
method call time=1647951801.228575 sender=:1.32 -> destination=org.freedesktop.DBus serial=62 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1647951801.228756 sender=:1.32 -> destination=org.freedesktop.DBus serial=63 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
method return time=1647951801.228769 sender=org.freedesktop.DBus -> destination=:1.32 serial=28 reply_serial=63
   string ":1.21"
method call time=1647951801.229064 sender=:1.32 -> destination=org.freedesktop.Notifications serial=64 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "KeePassXC"
   uint32 0
   string "keepassxc"
   string "KeePassXC"
   string "1 entrée était utilisée par electron"
   array [
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "org.keepassxc.KeePassXC"
      )
   ]
   int32 10000
method return time=1647951801.229110 sender=:1.32 -> destination=:1.73 serial=65 reply_serial=33
   array [
      dict entry(
         object path "/org/freedesktop/secrets/collection/password/<redacted>"
         struct {
            object path "/org/freedesktop/secrets/session/<redacted>"
            array of bytes [
               <redacted>
            ]
            array of bytes [
               <redacted>
            ]
            string "text/plain"
         }
      )
   ]
method return time=1647951801.288767 sender=:1.21 -> destination=:1.32 serial=973 reply_serial=64
   uint32 27
```
</details>
<details>
<summary>2.7.0 log</summary>

```
method call time=1647952147.393544 sender=:1.82 -> destination=:1.79 serial=28 path=/org/freedesktop/secrets; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.Secret.Service"
method call time=1647952147.393720 sender=:1.79 -> destination=org.freedesktop.DBus serial=50 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionUnixProcessID
   string ":1.82"
method return time=1647952147.393728 sender=org.freedesktop.DBus -> destination=:1.79 serial=23 reply_serial=50
   uint32 10601
method call time=1647952147.394221 sender=:1.79 -> destination=org.freedesktop.DBus serial=51 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetConnectionUnixProcessID
   string ":1.82"
method return time=1647952147.394235 sender=org.freedesktop.DBus -> destination=:1.79 serial=24 reply_serial=51
   uint32 10601
method call time=1647952147.395000 sender=:1.79 -> destination=org.freedesktop.DBus serial=52 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.82',arg2=''"
method return time=1647952147.395013 sender=:1.79 -> destination=:1.82 serial=53 reply_serial=28
   array [
      dict entry(
         string "Collections"
         variant             array [
               object path "/org/freedesktop/secrets/collection/password"
            ]
      )
   ]
method call time=1647952147.399204 sender=:1.82 -> destination=:1.79 serial=29 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=OpenSession
   string "dh-ietf1024-sha256-aes128-cbc-pkcs7"
   variant       array of bytes [
         <redacted>
      ]
method return time=1647952147.401578 sender=:1.79 -> destination=:1.82 serial=54 reply_serial=29
   variant       array of bytes [
         <redacted>
      ]
   object path "/org/freedesktop/secrets/session/<redacted>"
method call time=1647952147.404270 sender=:1.82 -> destination=:1.79 serial=30 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "account"
         string "<redacted>"
      )
      dict entry(
         string "service"
         string "element.io"
      )
      dict entry(
         string "xdg:schema"
         string "org.freedesktop.Secret.Generic"
      )
   ]
method return time=1647952147.404769 sender=:1.79 -> destination=:1.82 serial=55 reply_serial=30
   array [
   ]
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
method call time=1647952147.405248 sender=:1.82 -> destination=:1.79 serial=31 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=Unlock
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
method return time=1647952147.405777 sender=:1.79 -> destination=:1.82 serial=56 reply_serial=31
   array [
   ]
   object path "/org/freedesktop/secrets/prompt/<redacted>"
method call time=1647952147.407693 sender=:1.82 -> destination=:1.79 serial=38 path=/org/freedesktop/secrets/prompt/<redacted>; interface=org.freedesktop.Secret.Prompt; member=Prompt
   string ""
method return time=1647952147.407998 sender=:1.79 -> destination=:1.82 serial=57 reply_serial=38
signal time=1647952156.975361 sender=:1.79 -> destination=(null destination) serial=58 path=/org/freedesktop/secrets/prompt/<redacted>; interface=org.freedesktop.Secret.Prompt; member=Completed
   boolean false
   variant       array [
         object path "/org/freedesktop/secrets/collection/password/<redacted>"
      ]
method call time=1647952156.977167 sender=:1.82 -> destination=:1.79 serial=41 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=GetSecrets
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
   object path "/org/freedesktop/secrets/session/<redacted>"
method call time=1647952157.023818 sender=:1.79 -> destination=org.freedesktop.DBus serial=59 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1647952157.023934 sender=:1.79 -> destination=org.freedesktop.DBus serial=60 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
method return time=1647952157.023957 sender=org.freedesktop.DBus -> destination=:1.79 serial=25 reply_serial=60
   string ":1.21"
method call time=1647952157.024636 sender=:1.79 -> destination=org.freedesktop.Notifications serial=61 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "KeePassXC"
   uint32 0
   string "keepassxc"
   string "KeePassXC"
   string "1 entrée a été utilisée par /usr/lib/electron/electron"
   array [
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "org.keepassxc.KeePassXC"
      )
   ]
   int32 10000
method return time=1647952157.024829 sender=:1.79 -> destination=:1.82 serial=62 reply_serial=41
   array [
      dict entry(
         object path "/org/freedesktop/secrets/collection/password/<redacted>"
         struct {
            object path "/org/freedesktop/secrets/session/<redacted>"
            array of bytes [
               <redacted>
            ]
            array of bytes [
               <redacted>
            ]
            string "text/plain"
         }
      )
   ]
method return time=1647952157.102232 sender=:1.21 -> destination=:1.79 serial=1083 reply_serial=61
   uint32 28
method call time=1647952157.171967 sender=:1.82 -> destination=:1.79 serial=43 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=SearchItems
   array [
      dict entry(
         string "account"
         string "<redacted>"
      )
      dict entry(
         string "service"
         string "element.io"
      )
      dict entry(
         string "xdg:schema"
         string "org.freedesktop.Secret.Generic"
      )
   ]
method return time=1647952157.172954 sender=:1.79 -> destination=:1.82 serial=63 reply_serial=43
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
   array [
   ]
method call time=1647952157.173383 sender=:1.82 -> destination=:1.79 serial=44 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=GetSecrets
   array [
      object path "/org/freedesktop/secrets/collection/password/<redacted>"
   ]
   object path "/org/freedesktop/secrets/session/<redacted>"
method call time=1647952157.173995 sender=:1.79 -> destination=org.freedesktop.Notifications serial=64 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "KeePassXC"
   uint32 0
   string "keepassxc"
   string "KeePassXC"
   string "1 entrée a été utilisée par /usr/lib/electron/electron"
   array [
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "org.keepassxc.KeePassXC"
      )
   ]
   int32 10000
method return time=1647952157.174075 sender=:1.79 -> destination=:1.82 serial=65 reply_serial=44
   array [
      dict entry(
         object path "/org/freedesktop/secrets/collection/password/<redacted>"
         struct {
            object path "/org/freedesktop/secrets/session/<redacted>"
            array of bytes [
               <redacted>
            ]
            array of bytes [
               <redacted>
            ]
            string "text/plain"
         }
      )
   ]
error time=1647952157.227385 sender=:1.21 -> destination=:1.79 error_name=org.freedesktop.Notifications.Error.ExcessNotificationGeneration reply_serial=64
   string "Created too many similar notifications in quick succession"
```
</details>

**Comment by Aetf** [comment]
Hmm, with 2.7.0 it seems element desktop is requesting the password twice in very quick succession.
But KPXC replied both successfully. Are there any errors reported on the element desktop side?

**Comment by networkException** [comment]
I'm getting the following error:
```
2022-03-22T17:08:08.609Z E Unable to load session Error decrypting secret access_token: bad MAC
Error: Error decrypting secret access_token: bad MAC
    at vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1006213
    at async Q (vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1148708)
    at async Object.z (vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1144529)
2022-03-22T17:08:08.613Z I Starting load of AsyncWrapper for modal
2022-03-22T17:08:45.033Z I Starting load of AsyncWrapper for modal
2022-03-22T17:08:47.804Z I Got pickle key
2022-03-22T17:08:47.805Z E Unable to load session Error decrypting secret access_token: bad MAC
Error: Error decrypting secret access_token: bad MAC
    at vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1006213
    at async Q (vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1148708)
    at async z (vector://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:1144529)
```


Which causes element to display this dialog
![image](https://user-images.githubusercontent.com/42888162/159536863-743c424b-df60-4a49-9e93-dca96f1cb9fa.png)

**Comment by ArchangeGabriel** [comment]
What I have is in security settings:

Unable to load key backup status
<details open=""><summary>Advanced</summary>

Backup key stored: | not stored
Backup key cached: | not found locally
Secret storage public key: | not found
Secret storage: | not ready

</details>

And in any encrypted conversation:
>Unable to decrypt: Encryption not enabled

Looking at integrated developer tools (electron):
```
rageshake.ts:72 Unable to initialise e2e Error: OLM.BAD_ACCOUNT_KEY
    at ://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4111641
    at Ce.<anonymous> (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4114520)
    at Ce.unpickle (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4111347)
    at ://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:2089828
    at IDBRequest.n.onsuccess (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4277860)
e.<computed> @ rageshake.ts:72
```
```
Uncaught (in promise) Error: End-to-end encryption disabled
    at $.getEventEncryptionInfo (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:300811)
    at i.verifyEvent (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:700569)
    at i.UNSAFE_componentWillMount (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:696160)
    at _o (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4168656)
    at Ua (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4186944)
    at Vs (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4230635)
    at wc (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4216591)
    at Ec (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4216519)
    at yc (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4216382)
    at hc (://vector/webapp/bundles/cc857b0becf81e6a6db4/vendors~init.js:2:4213369)
```
But I did not have @networkException message however. And there is nothing in the terminal I run it from.

**Comment by networkException** [comment]
I just logged out and in again and it seems to work fine, probably just some rare edge case

**Comment by ArchangeGabriel** [comment]
Well logout/login means resetting the keys, no? So maybe starting from scratch works, but upgrading and keeping the keys does not, at least for me.

**Comment by Aetf** [comment]
So running 2.6 still works fine with element desktop right? Maybe the returned password somehow changed between 2.6 and 2.7.

It would be great if any of you can run the following python script to see exactly what are returned from KPXC
in 2.6 and 2.7, and manually verify that they are the same?

```python
import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
items = list(collection.search_items({'service': 'element.io', 'xdg:schema': 'org.freedesktop.Secret.Generic'}))
for item in items:
    print(item.get_secret())
```

This requires the python package `secretstorage` https://secretstorage.readthedocs.io/en/latest/index.html

**Comment by ArchangeGabriel** [comment]
@Aetf That codes returns this:
```python
---------------------------------------------------------------------------
LockedException                           Traceback (most recent call last)
Input In [1], in <cell line: 5>()
      4 items = list(collection.search_items({'service': 'element.io', 'xdg:schema': 'org.freedesktop.Secret.Generic'}))
      5 for item in items:
----> 6     print(item.get_secret())

File /usr/lib/python3.10/site-packages/secretstorage/item.py:96, in Item.get_secret(self)
     94 def get_secret(self) -> bytes:
     95 	"""Returns item secret (bytestring)."""
---> 96 	self.ensure_not_locked()
     97 	if not self.session:
     98 		self.session = open_session(self.connection)

File /usr/lib/python3.10/site-packages/secretstorage/item.py:48, in Item.ensure_not_locked(self)
     45 """If collection is locked, raises
     46 :exc:`~secretstorage.exceptions.LockedException`."""
     47 if self.is_locked():
---> 48 	raise LockedException('Item is locked!')

LockedException: Item is locked!
```
My database is unlocked of course.

**Comment by Aetf** [comment]
Ah sorry, each item needs to be unlocked to first trigger the authorization prompt.

Try this
```python
import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
items = list(collection.search_items({'service': 'element.io', 'xdg:schema': 'org.freedesktop.Secret.Generic'}))
for item in items:
    item.unlock()
    print(item.get_secret())
```

**Comment by ArchangeGabriel** [comment]
OK, this now works and the returned result is the same on both 2.6.6 and 2.7.

**Comment by Aetf** [comment]
Hmm, I run out of ideas about how to proceed...

Maybe report this to Element Desktop? It's still possible that the big refactor introduced in 2.7 changed behavior somehow.
But it's hard to pinpoint without knowing what exactly going wrong inside Element Desktop.

**Comment by michaelk83** [comment]
My guess is this has something to do with how unlocking is handled in 2.7.0? From a quick look at the DBus traces, I notice that with 2.6.6 there's no Unlock call, and only one Notify call. The error at the end of the 2.7.0 trace is regarding the Notify calls, though I don't know if that has anything to do with the main failure on Element Desktop's end.

**Comment by Aetf** [comment]
@ArchangeGabriel does 2.7.0 work if you disable "confirm when passwords are retrieved by clients"?

The Notify call fails because the two `GetSecrets` calls happen too fast, and KPXC tries to show desktop notification too
fast. But that shouldn't affect its interaction with element desktop.

**Comment by ArchangeGabriel** [comment]
No, it still does not work with that setting disabled… Since no-one else excepted @networkException reported issue with that (we did not have any report on both package in Arch), I’ll try the logout/login way (after making a backup of my session) and report.

**Comment by ArchangeGabriel** [comment]
OK, worst decision ever… So logout/login works as far as this issue is concerned, but in the process I’ve lost much more than my sessions keys (which are not that important), because what I’ve lost is the message history older than one year that is apparently not kept on the homeserver (at least the one I use) and was only available in my local client… and apparently you cannot in fact restore a session. Terrible way to start a day.

Anyway, this has nothing to do anymore with KeePassXC and I cannot even restore the previous state to keep debugging, so I guess I can now just close this ticket…

**Comment by ArchangeGabriel** [comment]
In case it happens to anyone else, the mistake to not do in order to not loose your backup, is to log out. Just don’t do that, instead after backing it up remove the local `.config/Element` folder (or `.config/Riot` if you have been using it for a while) while Element is closed and then restart Element. That will allow you to login again without loosing the ability to restore the backup, which is what happened to me…
