### ISSUE TITLE
Segmentation fault when a secret is requested

### ISSUE THREAD

**Issue by tbjep** [keepassxreboot/keepassxc#7922]
## Overview
Whenever a program requests a secret from the Keyring, KeepassXC throws a segmentation fault.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock a database with secrets enabled.
2. Open a program like GNOME Evolution and get it to ask for a secret.

## Expected Behavior
Evolution gets the secret and KeepassXC continues to run.

## Actual Behavior
KeepassXC crashes with a segmentation fault.

## Context
I usually the version directly from the Arch Linux repos and also tried the AppImage and built it from source.
Backtrace from the crash (built from source at the 2.7.1 tag):
```
#0  FdoSecrets::Item::ensureBackend (this=this@entry=0x0)
    at /dev/shm/keepassxc/src/fdosecrets/objects/Item.cpp:341
#1  0x00005555557eee95 in FdoSecrets::Item::locked (this=0x0, client=..., locked=@0x7fffffffd340: true)
    at /dev/shm/keepassxc/src/fdosecrets/objects/Item.cpp:81
#2  0x00005555557e29ea in FdoSecrets::Service::searchItems (this=<optimized out>, client=..., attributes=...,
    unlocked=..., locked=...) at /dev/shm/keepassxc/src/fdosecrets/objects/Service.cpp:262
#3  0x00005555557c0750 in FdoSecrets::Service::qt_static_metacall (_o=<optimized out>, _c=<optimized out>,
    _id=<optimized out>, _a=0x7fffffffd4d0)
    at /dev/shm/keepassxc/build/src/fdosecrets/fdosecrets_autogen/64PJ3GCGVF/moc_Service.cpp:243
#4  0x00005555557c1cc1 in FdoSecrets::Service::qt_metacall (this=0x5555560905c0,
    _c=QMetaObject::InvokeMetaMethod, _id=18, _a=0x7fffffffd4d0)
    at /dev/shm/keepassxc/build/src/fdosecrets/fdosecrets_autogen/64PJ3GCGVF/moc_Service.cpp:340
#5  0x00005555557dc3a6 in FdoSecrets::DBusMgr::deliverMethod (client=..., obj=<optimized out>, method=...,
    args=..., ret=..., outputArgs=...) at /usr/include/qt/QtCore/qvarlengtharray.h:189
#6  0x00005555557de82d in FdoSecrets::DBusMgr::activateObject (this=0x55555608a6c0, client=..., path=...,
    req=..., msg=...) at /dev/shm/keepassxc/src/fdosecrets/dbus/DBusDispatch.cpp:282
#7  0x00005555557dfb73 in FdoSecrets::DBusMgr::handleMessage (this=0x55555608a6c0, message=...)
    at /dev/shm/keepassxc/src/fdosecrets/dbus/DBusDispatch.cpp:197
#8  0x00007ffff7137a18 in ?? () from /usr/lib/libQt5DBus.so.5
#9  0x00007ffff7137e4c in ?? () from /usr/lib/libQt5DBus.so.5
#10 0x00007ffff68307d6 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff784d1c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff680c5aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff680d0a9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/libQt5Core.so.5
#14 0x00007ffff6854678 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007ffff4f4e163 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff4fa49e9 in ?? () from /usr/lib/libglib-2.0.so.0
#17 0x00007ffff4f4b6c5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff685857a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#19 0x00007ffff680488b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff680ffd7 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#21 0x00005555555e887e in main (argc=<optimized out>, argv=<optimized out>) at /dev/shm/keepassxc/src/main.cpp:187
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux
Desktop Env: bspwm
Windowing System: X11

**Comment by Aetf** [comment]
This is #7850. It is still unknown what is the root cause, though.
