### ISSUE TITLE
FdoSecrets crash on `searchItems`

### ISSUE THREAD

**Issue by the-nic** [keepassxreboot/keepassxc#8560]
## Overview
I see a crash 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. start vs code with two extensions enabled that try to use the secrets api (concurrently?)

## Expected Behavior
No crash

## Actual Behavior

Crash with the following stacktrace:

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
FdoSecrets::Item::ensureBackend (this=this@entry=0x0) at /home/nic/projects/keepassxc/src/fdosecrets/objects/Item.cpp:341
341             if (!m_backend) {
(gdb) bt
#0  FdoSecrets::Item::ensureBackend (this=this@entry=0x0) at /home/nic/projects/keepassxc/src/fdosecrets/objects/Item.cpp:341
#1  0x00005555558a24d9 in FdoSecrets::Item::locked (this=0x0, client=..., locked=@0x7fffffffce68: 224) at /home/nic/projects/keepassxc/src/fdosecrets/objects/Item.cpp:81
#2  0x0000555555891a82 in FdoSecrets::Service::searchItems (this=this@entry=0x555555f2fde0, client=..., attributes=..., unlocked=..., locked=...) at /home/nic/projects/keepassxc/src/fdosecrets/objects/Service.cpp:262
#3  0x000055555586709a in FdoSecrets::Service::qt_static_metacall (_o=_o@entry=0x555555f2fde0, _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=18, _a=_a@entry=0x7fffffffcfc0)
    at /home/nic/projects/build/keepassxc/src/fdosecrets/fdosecrets_autogen/64PJ3GCGVF/moc_Service.cpp:243
#4  0x0000555555867ba3 in FdoSecrets::Service::qt_metacall (this=0x555555f2fde0, _c=QMetaObject::InvokeMetaMethod, _id=18, _a=0x7fffffffcfc0) at /home/nic/projects/build/keepassxc/src/fdosecrets/fdosecrets_autogen/64PJ3GCGVF/moc_Service.cpp:340
#5  0x0000555555888576 in FdoSecrets::DBusMgr::deliverMethod (client=..., obj=<optimized out>, method=..., args=..., ret=..., outputArgs=...) at /home/nic/projects/keepassxc/src/fdosecrets/dbus/DBusDispatch.cpp:365
#6  0x000055555588cf07 in FdoSecrets::DBusMgr::activateObject (this=0x5555561a3b10, client=..., path=..., req=..., msg=...) at /home/nic/projects/keepassxc/src/fdosecrets/dbus/DBusDispatch.cpp:282
#7  0x000055555588dbd3 in FdoSecrets::DBusMgr::handleMessage (this=0x5555561a3b10, message=...) at /home/nic/projects/keepassxc/src/fdosecrets/dbus/DBusDispatch.cpp:197
#8  0x00007ffff6e65fb9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#9  0x00007ffff6e690cc in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#10 0x00007ffff64e7d09 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff77dee43 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff77e7c58 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff64ba03a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff64bc941 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff6515527 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff4a6417d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff4a64400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff4a644a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff6514b82 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff64b8b3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff64c0ce4 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x000055555560860c in main (argc=<optimized out>, argv=<optimized out>) at /home/nic/projects/keepassxc/src/main.cpp:187
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: release

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by michaelk83** [comment]
https://github.com/keepassxreboot/keepassxc/issues/7933#issuecomment-1114955937

**Comment by droidmonkey** [comment]
Ahh, @the-nic can you try a snapshot build to confirm your issue is corrected already? Https://snapshot.keepassxc.org

**Comment by the-nic** [comment]
Seems to work on the snapshots, thanks! -> Closing
