### ISSUE TITLE
Crash if the database becomes locked when fdosecrets access dialog is open

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#9104]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeePassXC crashes if the database becomes locked when fdosecrets access dialog is open. Looks like the access dialog attempts to acess entries from the locked database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Check "Confirm when passwords are retrieved by clients" in Settings -> Secret Service
2. Request a password (ex: `secret-tool lookup Title XYZ`)
3. Lock the database (ex: from the systray)
4. Cancel the access dialog

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

No crash.

By the way, the browser access dialog is rejected is the database is locked: https://github.com/keepassxreboot/keepassxc/blob/5bd871528fec3333e3f51bbac3e78662c8a9dbc3/src/browser/BrowserService.cpp#L417

Probably fdosecrets access dialog can do something similar?

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Backtrace with keepassxc 5bd871528:

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff681a07d in QMetaObject::cast (this=0x555555ae8c20 <Entry::staticMetaObject>, obj=0x555557690bf0) at kernel/qmetaobject.cpp:389
#2  0x00007ffff681a0ba in QMetaObject::cast (this=<optimized out>, obj=<optimized out>) at kernel/qmetaobject.cpp:378
#3  0x00005555557da1be in qobject_cast<Entry*> (object=<optimized out>) at /usr/include/qt/QtCore/qobject.h:519
#4  QtPrivate::QVariantValueHelper<Entry*>::object (v=...) at /usr/include/qt/QtCore/qvariant.h:753
#5  QtPrivate::ObjectInvoker<QtPrivate::QVariantValueHelper<Entry*>, QVariant const&, Entry*>::invoke (a=...) at /usr/include/qt/QtCore/qvariant.h:107
#6  qvariant_cast<Entry*> (v=...) at /usr/include/qt/QtCore/qvariant.h:879
#7  QVariant::value<Entry*> (this=0x7fffffffc5b0) at /usr/include/qt/QtCore/qvariant.h:367
#8  AccessControlDialog::dialogFinished (this=0x7fffec018e80, result=<optimized out>)
    at /usr/src/debug/keepassxc-git/keepassxc/src/fdosecrets/widgets/AccessControlDialog.cpp:190
#9  0x00007ffff684ba71 in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=<optimized out>, this=<optimized out>, this=<optimized out>, r=<optimized out>,
    a=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#10 doActivate<false> (sender=0x7fffec018e80, signal_index=7, argv=0x7fffffffc740) at kernel/qobject.cpp:3923
#11 0x00007ffff7a44163 in QDialog::finished (this=<optimized out>, _t1=<optimized out>) at .moc/moc_qdialog.cpp:230
#12 0x00007ffff7883721 in QWidget::event (this=0x7fffec018e80, event=0x7fffffffcc30) at kernel/qwidget.cpp:8704
#13 0x00007ffff784cb5c in QApplicationPrivate::notify_helper (this=this@entry=0x555555b371e0, receiver=receiver@entry=0x7fffec018e80, e=e@entry=0x7fffffffcc30)
    at kernel/qapplication.cpp:3640
#14 0x00007ffff7851e38 in QApplication::notify (this=<optimized out>, receiver=0x7fffec018e80, e=0x7fffffffcc30) at kernel/qapplication.cpp:3002
#15 0x00007ffff681af48 in QCoreApplication::notifyInternal2 (receiver=0x55555773f360, event=0x7fffffffcc30) at kernel/qcoreapplication.cpp:1064
#16 0x00007ffff78a32db in QWidgetWindow::handleGestureEvent (e=<optimized out>, this=<optimized out>) at kernel/qwidgetwindow.cpp:1122
#17 QWidgetWindow::event (this=0x55555774bf70, event=0x7fffffffcc30) at kernel/qwidgetwindow.cpp:371
#18 0x00007ffff784cb5c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x55555774bf70, e=0x7fffffffcc30) at kernel/qapplication.cpp:3640
#19 0x00007ffff681af48 in QCoreApplication::notifyInternal2 (receiver=0x55555774bf70, event=0x7fffffffcc30) at kernel/qcoreapplication.cpp:1064
#20 0x00007ffff6bef9d0 in QGuiApplicationPrivate::processKeyEvent (e=0x5555572c4610) at kernel/qguiapplication.cpp:2417
#21 0x00007ffff6bd8885 in QWindowSystemInterface::sendWindowSystemEvents (flags=flags@entry=...) at kernel/qwindowsysteminterface.cpp:1169
#22 0x00007ffff250a8d0 in xcbSourceDispatch (source=<optimized out>) at /usr/src/debug/qt5-base/qtbase/src/plugins/platforms/xcb/qxcbeventdispatcher.cpp:105
#23 0x00007ffff4db382b in g_main_dispatch (context=0x7fffec005010) at ../glib/glib/gmain.c:3454
#24 g_main_context_dispatch (context=0x7fffec005010) at ../glib/glib/gmain.c:4172
#25 0x00007ffff4e0acc9 in g_main_context_iterate.constprop.0 (context=0x7fffec005010, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4248
#26 0x00007ffff4db20e2 in g_main_context_iteration (context=0x7fffec005010, may_block=1) at ../glib/glib/gmain.c:4313
#27 0x00007ffff6865c6c in QEventDispatcherGlib::processEvents (this=0x555555c7eaa0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#28 0x00007ffff68136ec in QEventLoop::exec (this=0x7fffffffcf30, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#29 0x00007ffff681e219 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#30 0x00007ffff6be9fe2 in QGuiApplication::exec () at kernel/qguiapplication.cpp:1870
#31 0x00007ffff784af2a in QApplication::exec () at kernel/qapplication.cpp:2832
#32 0x00005555556077b1 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/keepassxc-git/keepassxc/src/main.cpp:218
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

The issue can be reproduced with a recent git commit (5bd871528) as well

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux up-to-date
Desktop Env: LXQt
Windowing System: X11

**Comment by droidmonkey** [comment]
This is going to require a fair amount of rearchitecture to corret.
